const STORAGE_KEY = 'album-tags-v1';
const sampleAlbums = [
  {id:'a1',name:'2406 부산 여행',date:'2024-06',count:182,tags:['여자친구','여행','부산']},
  {id:'a2',name:'2308 제주 가족 여행',date:'2023-08',count:421,tags:['여자친구','가족','사촌','여행','제주']},
  {id:'a3',name:'2205 한양대 동문 체육대회',date:'2022-05',count:76,tags:['한양대','동문','모임']},
  {id:'a4',name:'1907 강릉 여행',date:'2019-07',count:210,tags:['군대','여행','강릉']},
  {id:'a5',name:'1501 PPP 캠프',date:'2015-01',count:93,tags:['부산대','PPP','캠프']},
  {id:'a6',name:'2412 크리스마스',date:'2024-12',count:58,tags:[]}
];
let albums = loadAlbums();
let selectedTags = new Set(); let matchMode = 'all'; let showUntagged = false; let editingId = null;
const $ = s => document.querySelector(s);
function loadAlbums(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)) || sampleAlbums}catch{return sampleAlbums}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(albums))}
function allTags(){return [...new Set(albums.flatMap(a=>a.tags))].sort((a,b)=>a.localeCompare(b,'ko'))}
function filtered(){const q=$('#searchInput').value.trim().toLowerCase();let out=albums.filter(a=>{const query=!q||a.name.toLowerCase().includes(q)||a.tags.some(t=>t.toLowerCase().includes(q));const tagMatch=!selectedTags.size||(matchMode==='all'?[...selectedTags].every(t=>a.tags.includes(t)):[...selectedTags].some(t=>a.tags.includes(t)));return query&&tagMatch&&(!showUntagged||!a.tags.length)});const sort=$('#sortSelect').value;return out.sort((a,b)=>sort==='name'?a.name.localeCompare(b.name,'ko'):sort==='oldest'?a.date.localeCompare(b.date):b.date.localeCompare(a.date))}
function render(){const tags=allTags(), filters=$('#tagFilters');filters.innerHTML=tags.length?tags.map(t=>`<button class="chip ${selectedTags.has(t)?'selected':''}" data-tag="${escapeHtml(t)}"># ${escapeHtml(t)}</button>`).join(''):'<span class="filter-label">아직 태그가 없어요. 앨범을 열어 태그를 추가해 보세요.</span>';filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{const t=b.dataset.tag;selectedTags.has(t)?selectedTags.delete(t):selectedTags.add(t);showUntagged=false;render()});$('#untaggedButton').classList.toggle('active',showUntagged);$('#matchModeButton').textContent=matchMode==='all'?'모두 포함':'하나라도 포함';$('#matchModeButton').disabled=selectedTags.size<2;const list=filtered();$('#resultTitle').textContent=showUntagged?'미분류 앨범':selectedTags.size?'선택한 태그의 앨범':'모든 앨범';$('#resultCount').textContent=`${list.length}개 앨범`;const grid=$('#albumGrid');grid.innerHTML='';if(!list.length){grid.innerHTML='<div class="empty"><strong>조건에 맞는 앨범이 없어요.</strong><br><br>검색어나 태그 필터를 바꿔 보세요.</div>';return}const template=$('#albumTemplate');list.forEach(a=>{const node=template.content.cloneNode(true),card=node.querySelector('.album-card');node.querySelector('.cover').onclick=()=>openDialog(a.id);node.querySelector('.cover-month').textContent=a.date.replace('-','.');node.querySelector('h3').textContent=a.name;node.querySelector('.album-meta').textContent=`사진 ${a.count.toLocaleString()}장`;node.querySelector('.album-tags').innerHTML=a.tags.length?a.tags.map(t=>`<span># ${escapeHtml(t)}</span>`).join(''):'<span style="background:#f2f2f5;color:#777">태그 없음</span>';grid.append(node)})}
function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function parseTags(text){return [...new Set(text.split(',').map(t=>t.trim().replace(/^#/,'')).filter(Boolean))]}
function openDialog(id=null){editingId=id;const a=albums.find(x=>x.id===id);$('#dialogHeading').textContent=a?'앨범 편집':'앨범 추가';$('#albumNameInput').value=a?.name||'';$('#albumDateInput').value=a?.date||new Date().toISOString().slice(0,7);$('#photoCountInput').value=a?.count||0;$('#tagsInput').value=a?.tags.join(', ')||'';$('#deleteButton').hidden=!a;renderSuggestions();$('#albumDialog').showModal();$('#albumNameInput').focus()}
function renderSuggestions(){const current=parseTags($('#tagsInput').value);$('#tagSuggestions').innerHTML=allTags().filter(t=>!current.includes(t)).slice(0,12).map(t=>`<button type="button" class="chip" data-add="${escapeHtml(t)}">+ ${escapeHtml(t)}</button>`).join('');$('#tagSuggestions').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#tagsInput').value=parseTags(`${$('#tagsInput').value},${b.dataset.add}`).join(', ');renderSuggestions()})}
$('#newAlbumButton').onclick=()=>openDialog();$('#closeDialog').onclick=$('#cancelButton').onclick=()=>$('#albumDialog').close();$('#albumForm').onsubmit=e=>{e.preventDefault();const value={id:editingId||crypto.randomUUID(),name:$('#albumNameInput').value.trim(),date:$('#albumDateInput').value,count:Number($('#photoCountInput').value)||0,tags:parseTags($('#tagsInput').value)};if(editingId)albums=albums.map(a=>a.id===editingId?value:a);else albums.push(value);save();$('#albumDialog').close();render()};$('#deleteButton').onclick=()=>{albums=albums.filter(a=>a.id!==editingId);save();$('#albumDialog').close();render()};$('#tagsInput').addEventListener('input',renderSuggestions);$('#searchInput').oninput=render;$('#sortSelect').onchange=render;$('#untaggedButton').onclick=()=>{showUntagged=!showUntagged;selectedTags.clear();render()};$('#matchModeButton').onclick=()=>{matchMode=matchMode==='all'?'any':'all';render()};$('#clearFiltersButton').onclick=()=>{selectedTags.clear();showUntagged=false;$('#searchInput').value='';render()};$('#exportButton').onclick=()=>{const blob=new Blob([JSON.stringify(albums,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='album-tags-backup.json';a.click();URL.revokeObjectURL(url)};$('#importInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const parsed=JSON.parse(r.result);if(!Array.isArray(parsed))throw Error();albums=parsed;save();render();alert('앨범과 태그를 복원했어요.')}catch{alert('올바른 앨범태그 백업 파일이 아닙니다.')}};r.readAsText(f);e.target.value=''};render();
